[[WCS]]
arch = "aarch64"
git-tree-sha1 = "2b50015bf53a37451a08c6ab850f22b59ebf90a3"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "3dec41ae650235253656e56fd582461aa738c7ff9b6cf58a2da666ca83b79cfb"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.4.0+0/WCS.v7.4.0.aarch64-linux-gnu.tar.gz"
[[WCS]]
arch = "aarch64"
git-tree-sha1 = "e8f7d33d898d27f46a85198567922c2e7c20640b"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "60f3c1071229e1f180b92f532a539fcfc359bbd8f22bd5deccd298ed08a8761d"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.4.0+0/WCS.v7.4.0.aarch64-linux-musl.tar.gz"
[[WCS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9a1fb415649cd8a5215965994f9396f7350f34fa"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "1f89c1ee77f64cfc00293c550c624faaed70717ac1a491eea8c1ed3cda84ceeb"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.4.0+0/WCS.v7.4.0.armv7l-linux-gnueabihf.tar.gz"
[[WCS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "85acaba735b2bf5894e268c726f6c57162f55b46"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "29d1dc95d0bd318f3682bc6886d01bd79ea4f57e70ceefe376c59c0772a4a3c6"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.4.0+0/WCS.v7.4.0.armv7l-linux-musleabihf.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "49ecf2629eb4e9d0768f9f179a5156b674f83c60"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "59051bb50a7006a352c48c443480daf88538a88924c78c497fabf8cf650f2294"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.4.0+0/WCS.v7.4.0.i686-linux-gnu.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "efb5b7e408be25714f7d52377b00dd195c7b6b37"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "eeedba683cd56ff9d6cfbfbbcd4d3a15f6f2b147f21edcd3e63896752c01a321"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.4.0+0/WCS.v7.4.0.i686-linux-musl.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "6063667fa09616b433b8ed62b09c7689d6b62c28"
os = "windows"

    [[WCS.download]]
    sha256 = "73e3c9943b2b2f0564e5114d9b339e9424f409c2ede61cc437c475efdaf0dc35"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.4.0+0/WCS.v7.4.0.i686-w64-mingw32.tar.gz"
[[WCS]]
arch = "powerpc64le"
git-tree-sha1 = "17394578a2dc05cad7b5527e8c22e95e4637b204"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "a70a00a0b225f7326cac2c80d95ee30d36addb771a943dc5b570003a4cafdaab"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.4.0+0/WCS.v7.4.0.powerpc64le-linux-gnu.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "e278db0f7e62bcbc259e871c0fa39e405af864ed"
os = "macos"

    [[WCS.download]]
    sha256 = "2b44b06b02e19bf7d497de2c6d42534a15edcd081f835ce4d6f0e562d355044b"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.4.0+0/WCS.v7.4.0.x86_64-apple-darwin.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "b07454cd3e9707f663a195bf6018e6d477286462"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "eac331e3a91fe329b1672599387208753c4d99a792314907b2e49e095d811326"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.4.0+0/WCS.v7.4.0.x86_64-linux-gnu.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "7186ae756c40a0294e5d9898f833b0ac202e3154"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "f2d7ea82a6177f0de578a37e46b5d91fceb56e752fb8939a6cedcf87c5799914"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.4.0+0/WCS.v7.4.0.x86_64-linux-musl.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "d148d4823b4532ceda2b5507c8d60c61f32bcbc5"
os = "freebsd"

    [[WCS.download]]
    sha256 = "66f5508cdca817315d8be5eb52636b7b2386617da752ac0af129dbc49341861b"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.4.0+0/WCS.v7.4.0.x86_64-unknown-freebsd.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "cc87276e42d819abf56acfef41cf66fbd3bcaac8"
os = "windows"

    [[WCS.download]]
    sha256 = "24140cca078cdc23f15d0057f1a6f408b23da63551c2fad29ac6b1f09dde37ef"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.4.0+0/WCS.v7.4.0.x86_64-w64-mingw32.tar.gz"
