[[WCS]]
arch = "aarch64"
git-tree-sha1 = "5cdaafa4f24e6b34c8214fb2cb0fd80487ef64b1"
os = "macos"

    [[WCS.download]]
    sha256 = "19b3b7d635b1f278b1e1459760317b1561cf01c4e5f48887238e1c15fd9cadaa"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.7.0+0/WCS.v7.7.0.aarch64-apple-darwin.tar.gz"
[[WCS]]
arch = "aarch64"
git-tree-sha1 = "bd29711935f491815c6bff7b8f8fec346b33c318"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "fe9293053db18d083819606e3faff12d92da8e717b1d355dcb6aa3ff2ca19d68"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.7.0+0/WCS.v7.7.0.aarch64-linux-gnu.tar.gz"
[[WCS]]
arch = "aarch64"
git-tree-sha1 = "19e0e6b36e2d7df69879968b892900c5ad4baf06"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "a835b8efd8085edfb44649b2f2902829562860557637b00d484d5d8ad2a32cd9"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.7.0+0/WCS.v7.7.0.aarch64-linux-musl.tar.gz"
[[WCS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d36cb3d5d5f3d03f963e56e01c3ce95feffc421a"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "d3e2016d23cb3576ff17360d650f3e6ee15ca1335bd110f70d030abe3c7f142b"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.7.0+0/WCS.v7.7.0.armv6l-linux-gnueabihf.tar.gz"
[[WCS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "170066223b601673abac8323e7cc92289f2494ef"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "39904b708c24cefd7c4d3b88e388415efb0db989006b3f64f6395f9426fad832"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.7.0+0/WCS.v7.7.0.armv6l-linux-musleabihf.tar.gz"
[[WCS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "de4ef672101ae93a6393c5140b41d7017dba4279"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "0fbc3fe6c783dd596679fb4ae72fa23b6935dc2e7b04be5e209606bee10b49a2"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.7.0+0/WCS.v7.7.0.armv7l-linux-gnueabihf.tar.gz"
[[WCS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f3003b88308a108ad52cb4adc24f03c8ce90fa15"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "b9a447e9a152ab314f4ff63473e85e4fb14b7a9395d9bd6c167d03dadb6191df"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.7.0+0/WCS.v7.7.0.armv7l-linux-musleabihf.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "9cf5f7b302e9c2207c3a3089cfd0e8e579a38d64"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "edc4a39c60a68871dafd1a99e6c68f0da5c9a5bf90708cf9e20dd1d73d5eb76a"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.7.0+0/WCS.v7.7.0.i686-linux-gnu.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "cb500c0cc2cef6dfd4985a1d111487be0b235741"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "3e91c3dcf9aa0b61b9f3a0e737164fe371f5ee693948978465f50ce447344de9"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.7.0+0/WCS.v7.7.0.i686-linux-musl.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "f301f472efb43cd5c35bb4a216ff8965b4086dce"
os = "windows"

    [[WCS.download]]
    sha256 = "a63a077c5a85316e6fe9b9e092762adfccc76e7b70245ba3463dab2f10099109"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.7.0+0/WCS.v7.7.0.i686-w64-mingw32.tar.gz"
[[WCS]]
arch = "powerpc64le"
git-tree-sha1 = "e843404d879753fb19936c1264c90df803d73ba2"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "c98e79927bf921c868fc19f30d705e27b739cde8b2a2ef0d00fb8e4bae956638"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.7.0+0/WCS.v7.7.0.powerpc64le-linux-gnu.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "9d5ca573087dea58cb3bb5ff02c4bbb6618e94bc"
os = "macos"

    [[WCS.download]]
    sha256 = "9be21e995963639ed2f68ed29368dbf300f704f2f92f7c43af23e4f9f2e9004d"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.7.0+0/WCS.v7.7.0.x86_64-apple-darwin.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "c0c88f4d65d889a820fbcdbdd7af766684ee4310"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "33b45eeb59fc006b97e461405517f2cab34d85a50ea4e9da61e1573023751135"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.7.0+0/WCS.v7.7.0.x86_64-linux-gnu.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "28dee045b97bd861efa88434e2b4d233943ac914"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "580ded0d74e09b18af6c3ca7a50bdd617b991c2dbb956c3902e969d51076d495"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.7.0+0/WCS.v7.7.0.x86_64-linux-musl.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "1478fecaba50c87824503c0d3a1db085ba554319"
os = "freebsd"

    [[WCS.download]]
    sha256 = "505eb99b3572d498c260e42a6c70d1b63000b9f775e9d1c7c78d14bcc9933d91"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.7.0+0/WCS.v7.7.0.x86_64-unknown-freebsd.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "361ca04fce2b2bdd91762be634102f3efe71784e"
os = "windows"

    [[WCS.download]]
    sha256 = "c2d010e09653e5dfcff43dea9ffbf4bef8e5bed9298cdd8ecad68aa6c6c35eee"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.7.0+0/WCS.v7.7.0.x86_64-w64-mingw32.tar.gz"
