[[WCS]]
arch = "aarch64"
git-tree-sha1 = "7f8aa500fdd1490611071da11b4f2ac37f608937"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "f740e9ab0d138be6f5c2be74a9ffb2e39e8c68fd00b70ff2e1d7c49dcd0d6668"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.1+0/WCS.v7.3.1.aarch64-linux-gnu.tar.gz"
[[WCS]]
arch = "aarch64"
git-tree-sha1 = "233a95b73c399d8affba8d7dfb379d14acdc41da"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "1c99c71e8a67155f1adce0c14c3c51ac6b204ff0630d2e95dfe91aa8f4faf0d2"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.1+0/WCS.v7.3.1.aarch64-linux-musl.tar.gz"
[[WCS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "59eb6daea82d6b0038d71061d7206760586d9548"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "f2fae5410c2034c82489d0c707c090a2936f8cd2b6fb955d1e25ef1b4ab46a89"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.1+0/WCS.v7.3.1.armv7l-linux-gnueabihf.tar.gz"
[[WCS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aed6fad31b5526a4e8ce403dcfb5a8a79b1e07fc"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "6918c052845b42a9e4e1a0e6c851937154a51b3e4e59cc8f0f6fa2dbcf61d371"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.1+0/WCS.v7.3.1.armv7l-linux-musleabihf.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "f1ceb82defed7a9b00cb1a23d4cbd4dcc3c169fe"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "9da6f9ffa0083b513a665aa967bf5ab651f4ba0f2491752bfb095e28fc3f1c31"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.1+0/WCS.v7.3.1.i686-linux-gnu.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "4418909ec6b2d30fb9946ddff999c36454fc3f34"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "33fa9ab774cef597db2d1a76765714ab1f7fb9ef925099cde815fa8f5c3c7e6c"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.1+0/WCS.v7.3.1.i686-linux-musl.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "8299987986d537e6c8483686ca3193cc6597db2d"
os = "windows"

    [[WCS.download]]
    sha256 = "edb874a3811377af82218a6788fd183134d064d36f916c5eca946a6640850036"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.1+0/WCS.v7.3.1.i686-w64-mingw32.tar.gz"
[[WCS]]
arch = "powerpc64le"
git-tree-sha1 = "2b7ed7ea8a9d4f83f11b14d2456e13b6886e9905"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "626e343c47e143fcca4e58995d371bb50ba6e77e7a725c47c6b10cfe6fc6f284"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.1+0/WCS.v7.3.1.powerpc64le-linux-gnu.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "a88ada840fb58ed6b326b0efefecd7de723d355a"
os = "macos"

    [[WCS.download]]
    sha256 = "dfab68e6753d9aef48e0395ab64a5025259f8fab0639b1dee007ba9d7bd2a214"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.1+0/WCS.v7.3.1.x86_64-apple-darwin.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "1397114e40a32cc63314ffffa6618686a39d5b49"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "d070a7aa08b9b2b43b0ff2cfcce7c4049bbb7eb63a4f29a6b782c88b12981de8"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.1+0/WCS.v7.3.1.x86_64-linux-gnu.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "56543c92fb8c56526a4d966492935c9679ff8644"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "89956479cc2765fb7e71747b27b5af440d1d3175615133451a5040c4565adead"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.1+0/WCS.v7.3.1.x86_64-linux-musl.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "bf216058b9caf0712f849518cf8fc50da9a156c2"
os = "freebsd"

    [[WCS.download]]
    sha256 = "d44590e1b62bdee8098fd126ec14b37bf7b0c906e06fb47eeb4b47f25a052d79"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.1+0/WCS.v7.3.1.x86_64-unknown-freebsd.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "d7482762c86769a4ef2de77aefd5ed3667b277db"
os = "windows"

    [[WCS.download]]
    sha256 = "6454d3c9d6bf68c2fbac18f695fdb1dabd5b02d88b25dc8e3272c26a187353b0"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.1+0/WCS.v7.3.1.x86_64-w64-mingw32.tar.gz"
