[[WCS]]
arch = "i686"
git-tree-sha1 = "5e733a538ab48e58d26fb837543121d549384e9c"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "844e7dd4a40a703fef656f33e91ad3c4d4decc3372a5a9e0f3efd00800522d50"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.1.0+0/WCS.v7.1.0.i686-linux-musl.tar.gz"
[[WCS]]
arch = "aarch64"
git-tree-sha1 = "7c1e63ca0d0cd8d47303b8eabae220da5402ea06"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "975c2fa0ab1f6a930981a0f2abf2542fbb3d67a29fcb3c93820d3a5dccfd4f68"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.1.0+0/WCS.v7.1.0.aarch64-linux-musl.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "cfd0775a100dc975fca1f2c42b52003fa79ac927"
os = "windows"

    [[WCS.download]]
    sha256 = "ee02a2c0ab68dc007e93a6e3f438a32a2485afd47d8a1400f07a8547b519e25a"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.1.0+0/WCS.v7.1.0.i686-w64-mingw32.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "9d168990060fc74e147e0519770b374c82a0c535"
os = "windows"

    [[WCS.download]]
    sha256 = "51284336636ae1c0084974be96b187e8484e764156c72e32a69172ac9fb72632"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.1.0+0/WCS.v7.1.0.x86_64-w64-mingw32.tar.gz"
[[WCS]]
arch = "armv7l"
git-tree-sha1 = "20ef8cbd8c1aca224b671e771183fa71b4716859"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "cc25bad569cf2428489a67524364a9506370723f39640b1d5fbe9950ae3d0671"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.1.0+0/WCS.v7.1.0.armv7l-linux-gnueabihf.tar.gz"
[[WCS]]
arch = "armv7l"
git-tree-sha1 = "a6470bf21dddcc8ac8541dc1c8d2c3b4b8e7f2b9"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "0380f1c8957fe2ad9af71069b1ea455c8a0275f3cd80f3ec998beba7b7a4cea1"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.1.0+0/WCS.v7.1.0.armv7l-linux-musleabihf.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "affe221dcf282236552e6635bac587f0f0a3b0e3"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "bfbf25701ae9f3d04d11b124b746bbc064086bb1cf4abcfa95c42d15e48dd487"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.1.0+0/WCS.v7.1.0.i686-linux-gnu.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "2c4048127c27586ae3d13da98d07c6235886bd72"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "8387cabc72a1c1a5347b1118073e1a2e2b13eb00926a22782197dfee3cbf651b"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.1.0+0/WCS.v7.1.0.x86_64-linux-gnu.tar.gz"
[[WCS]]
arch = "powerpc64le"
git-tree-sha1 = "6df0a1b30bc3ed482bd5bdc38a5694ec765a76ea"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "4952e5083721ac06254809d7e83a0b6119c71a6de7a76918741b71616ad25262"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.1.0+0/WCS.v7.1.0.powerpc64le-linux-gnu.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "20236814a8990371f5f8a6d59e5e2e7a07175ca3"
os = "macos"

    [[WCS.download]]
    sha256 = "1041490d60dccf8c0233d517bb34b7ad36743582504c3f3a4153737d5741f4d5"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.1.0+0/WCS.v7.1.0.x86_64-apple-darwin14.tar.gz"
[[WCS]]
arch = "aarch64"
git-tree-sha1 = "909978dd5dfea666df5129864a142f6eefac2cd3"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "063d76339a66b546d429e2cc4ad3d4f2ec9cd69326ff4607d90583b5dd600fcd"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.1.0+0/WCS.v7.1.0.aarch64-linux-gnu.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "f03429ee4ff4be2744aa3ccbaeed1764861c8ef1"
os = "freebsd"

    [[WCS.download]]
    sha256 = "a9dcbdf3cb0acd9675f316ea1bfcaf7bd8f36fb765a5b16d08bbba8a6c79e78a"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.1.0+0/WCS.v7.1.0.x86_64-unknown-freebsd11.1.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "6a984c3d04aff424186a4e11f3d7268fd9c021ad"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "a20becb125dee5a846134f3ee3a16012137b48835b6f4d130f5b8c0cc1dfe94c"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.1.0+0/WCS.v7.1.0.x86_64-linux-musl.tar.gz"
