[[WCS]]
arch = "aarch64"
git-tree-sha1 = "fe2186da4dbf22627918a704e27af20fd2d1e405"
os = "macos"

    [[WCS.download]]
    sha256 = "e739b541f676798f43c689fc194549e1d8a14707711c818ee6e219c5d0a6eea9"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+0/WCS.v7.6.0.aarch64-apple-darwin.tar.gz"
[[WCS]]
arch = "aarch64"
git-tree-sha1 = "0a030a74d12e25175cc0c843c01ee1bd3f2a2937"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "4f016f97a80c55c852bb068a5c2e532c42d54728e305961c843529f90f6ede09"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+0/WCS.v7.6.0.aarch64-linux-gnu.tar.gz"
[[WCS]]
arch = "aarch64"
git-tree-sha1 = "4456dc3ee6e976e15692df54c765d85e741789fa"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "3cfd97bc159818faa5b4f897f4ab3e7bfa3f215d3659dedf1b045587467138b0"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+0/WCS.v7.6.0.aarch64-linux-musl.tar.gz"
[[WCS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4203b99ced0d59371a621275d37074c1dc5a11fd"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "7b1fa8104c62128eaf35085fe2ea1c5a6d4d56d2d4a12616f8658ebb6c19a961"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+0/WCS.v7.6.0.armv6l-linux-gnueabihf.tar.gz"
[[WCS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0d0148ce53d41abfe641a6cb42243e9f5fc6146c"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "2950d758fafcc9fca4efe10e23259c1d04e9ff2f141d847f2d52b6d206125b5d"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+0/WCS.v7.6.0.armv6l-linux-musleabihf.tar.gz"
[[WCS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "05eebef6503bd57b70265325119c282845ce5c1f"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "d325dbf602ddef72a1a0ce52db94d30a8eba96a6492587e09198d18a7b75ba37"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+0/WCS.v7.6.0.armv7l-linux-gnueabihf.tar.gz"
[[WCS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5e09c15dbf31193631478e87afe6cc881490f026"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "a6fbaec77912f3dab456d18821901e895521216c13d956906927377cc0bf3902"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+0/WCS.v7.6.0.armv7l-linux-musleabihf.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "3eb394c8193cf1ba3e4e104fe5c400bfca82354a"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "ceeb651240af07a59c96d806014776411e60e16a8f1be54fe8c961c242021d5c"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+0/WCS.v7.6.0.i686-linux-gnu.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "9cefde02871c9484fec51a803f2acd3d615eb079"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "31472c6701f2708694a9e23c1adde83e3cc21d19302e557ccd3f0f048b1604d1"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+0/WCS.v7.6.0.i686-linux-musl.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "1d5885152a52b4a804eb4483cbf860e0d7499d76"
os = "windows"

    [[WCS.download]]
    sha256 = "fa044485c0c2fc799ce35c837c3ecfefdc231222d160455ea974da1baadb1050"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+0/WCS.v7.6.0.i686-w64-mingw32.tar.gz"
[[WCS]]
arch = "powerpc64le"
git-tree-sha1 = "6235ddafa6fb33f38bc0d4d1897acdc3756cd8f5"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "02c756579972d12887306e834e2e6dd458cd584cc0ad1cef49fba4564225edaa"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+0/WCS.v7.6.0.powerpc64le-linux-gnu.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "6e6d6a99efd8bf57fb7c87c355e2c915b8ee0cb4"
os = "macos"

    [[WCS.download]]
    sha256 = "f4322c5af0ad30fd6049d228b9036ec7f184ee133dc8025ff75e710a6da8e7c2"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+0/WCS.v7.6.0.x86_64-apple-darwin.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "87728ba28d6995cc07440ec0da272a3868d034c3"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "f1d152d58e924d52691823813d326d0587720c4dd4464f94d38f61b904ba4f9f"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+0/WCS.v7.6.0.x86_64-linux-gnu.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "3424d986ed4df8c223ffffa4a0b6f3d3c7a4cac9"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "81e7ae134e56d0757335433ac91f1bd3671cc308aff21cccf072d8b5dff010b4"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+0/WCS.v7.6.0.x86_64-linux-musl.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "cf7c243cdf62d4827097da99fec746d6a809cd4e"
os = "freebsd"

    [[WCS.download]]
    sha256 = "1cb3afd392d286f4a02d22cfa5a041571512ac5c4d89fc57cd1d9ac5dd6c0c39"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+0/WCS.v7.6.0.x86_64-unknown-freebsd.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "617d3f2769a0af0e7b3dddaad984b2634ba6abc5"
os = "windows"

    [[WCS.download]]
    sha256 = "221210ee6c976db1712b7c4e60ebd878e6da476fdbfdd6e447d74e96bb4340b3"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+0/WCS.v7.6.0.x86_64-w64-mingw32.tar.gz"
