[[WCS]]
arch = "aarch64"
git-tree-sha1 = "b792303c038ae82df1537e4c2b510a9de57a5d71"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "057f16b02db854f8fa12bf9766e814a3968d6ec7af535b3b44dc9e2a71d3ce40"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.0+0/WCS.v7.3.0.aarch64-linux-gnu.tar.gz"
[[WCS]]
arch = "aarch64"
git-tree-sha1 = "ea76be469d160997e356b6864dbe6d7423e0eb40"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "4c29d812781da412d81ec06bc9084f4cc762777bf2e0d5320a8659612b8d1ac8"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.0+0/WCS.v7.3.0.aarch64-linux-musl.tar.gz"
[[WCS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a2437b246762f8616bd64e25eda9a4a2cc276b34"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "824168fc89d6f6214b3702898d410971e14e95e98fd6ce8b2d6b9243a4258a5f"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.0+0/WCS.v7.3.0.armv7l-linux-gnueabihf.tar.gz"
[[WCS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b9248dad805adc900fafd64e3f324b268c7e80e5"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "17600e36e62662ba9e8b4f8948d83b064be0e3990be57030e6cfc49e3ba5178a"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.0+0/WCS.v7.3.0.armv7l-linux-musleabihf.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "e46c60ea7c7ba6d1db5ea7349df4d33f2261077b"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "fe4507db12d762fe013e971b3b0c0e85ebbbaf992382fbfe9df1129032685cf1"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.0+0/WCS.v7.3.0.i686-linux-gnu.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "59f3d588825b705df1753169533810e23f1b9629"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "eb74278a89d7e140fe6a861443ab45d7313fd8fc9dabab85aba2f96590f95c34"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.0+0/WCS.v7.3.0.i686-linux-musl.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "74ab7086ed6cd28162e00a11b0bc91ec697c189a"
os = "windows"

    [[WCS.download]]
    sha256 = "6f7cd84e28c61b467c09921c3e47b60bc4055692e261dc531a215ee9dd754616"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.0+0/WCS.v7.3.0.i686-w64-mingw32.tar.gz"
[[WCS]]
arch = "powerpc64le"
git-tree-sha1 = "76ecc588ab0cf733d27192f8bafb283588fa2a23"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "2c5d72d05f7524fb1f4c55f35ee4d2577289ba49758f1190ea03d61e5b5b5a9f"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.0+0/WCS.v7.3.0.powerpc64le-linux-gnu.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "a63cb57bbd4a4b380db481b54a867122c9dad72b"
os = "macos"

    [[WCS.download]]
    sha256 = "e37f33e51cf2ffc7271d64c4f23e58d2b56398d7364439391ba78b5c2e16ec23"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.0+0/WCS.v7.3.0.x86_64-apple-darwin.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "b5b43f4aff773d412bf09ef728134fd57c3f4f0c"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "31a8a39e751464320139bcca419d6fe1c9473a9c30b206dcd2fe11cf5cb9f3a1"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.0+0/WCS.v7.3.0.x86_64-linux-gnu.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "fe6d1447542037c63fe41afeacf04cd6871455d5"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "876195aa34dee1355b2be84d35d27f0ebccb39e021da3396ba9b13a3a587907c"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.0+0/WCS.v7.3.0.x86_64-linux-musl.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "99f9fdccb9ad8ab82f04a1749879caa3f5c8ab77"
os = "freebsd"

    [[WCS.download]]
    sha256 = "7032ee6d64a405655cf33022458ebd5a9ed8cf68d5e14cb6fcdccd7f6bd42a7b"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.0+0/WCS.v7.3.0.x86_64-unknown-freebsd.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "b675f027ec98efbaf11d8714b4f59490b2c0c1e3"
os = "windows"

    [[WCS.download]]
    sha256 = "e0c076db2879908840cb85293e18a3a1b60d1eadd1754827be9c518ba84b0588"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.3.0+0/WCS.v7.3.0.x86_64-w64-mingw32.tar.gz"
