[[WCS]]
arch = "aarch64"
git-tree-sha1 = "a34aae045fa122d8deb5bf691512a44904cd6aaf"
os = "macos"

    [[WCS.download]]
    sha256 = "361afffb45bada6cbfb4adb9f5f2d5a2251b6aa6d784e931ad04690864dcd85a"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+1/WCS.v7.6.0.aarch64-apple-darwin.tar.gz"
[[WCS]]
arch = "aarch64"
git-tree-sha1 = "3efa8f44b1614f1a83659e9f7abbf5f3d51a35b8"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "9238299b4ec12eb2ae215329bf51d151418bd27834e69607f6a9fd6da47142f9"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+1/WCS.v7.6.0.aarch64-linux-gnu.tar.gz"
[[WCS]]
arch = "aarch64"
git-tree-sha1 = "a8e3b0e963c362b6d645fa24033ff11325e85d50"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "3d469045efd94fe0d3893e72b18b395960e8fb98310826bf58b182ef224a2fa0"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+1/WCS.v7.6.0.aarch64-linux-musl.tar.gz"
[[WCS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9ba53093fc8d33bab4b1c098ce5c33d2c7c9c6d4"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "63ada82fcd536a23a7019ed72c0409154e8db3e1beb06a6b3bb2b24fe3d28e32"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+1/WCS.v7.6.0.armv6l-linux-gnueabihf.tar.gz"
[[WCS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "057b6e821480b5b3270c17c8b8b54cc4c7e9b8aa"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "1b7128b38a958d64e9aa58cbcc08406737835604c6018d917218611476ee81d4"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+1/WCS.v7.6.0.armv6l-linux-musleabihf.tar.gz"
[[WCS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5744b3e8ca8f83373766ed99f9c698ff87edd4d0"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "4d44eaaf77b028f954de64225e6eff3feef0d00461f287f785407f612d908813"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+1/WCS.v7.6.0.armv7l-linux-gnueabihf.tar.gz"
[[WCS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e685914c35934e9540a4b0dc6c6236903acfaea4"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "9f8ce2d723453612fd2df560ded24b2d0331ccb78319d2535e8bcf35c2c52ad3"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+1/WCS.v7.6.0.armv7l-linux-musleabihf.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "e25ff20490465f9e7e782440d7f4a0f6cf54f7b9"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "743b328d65646e96fff4ab4f3f82e14a66176566979d5a1563e2768af2170218"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+1/WCS.v7.6.0.i686-linux-gnu.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "74be9472c66fdaa63ae3fc21183970bc30cdf8ee"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "dd722c548d05a409cb3e8eb5f51dace21bf536b5eeb4f50e8e327515b4e273b8"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+1/WCS.v7.6.0.i686-linux-musl.tar.gz"
[[WCS]]
arch = "i686"
git-tree-sha1 = "07df8f99d879461dac31428670ed88d91b9e5e40"
os = "windows"

    [[WCS.download]]
    sha256 = "34c96f96088762d66b663fa1fed6db21707a7f2b3c4b91b9c9157b1009789460"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+1/WCS.v7.6.0.i686-w64-mingw32.tar.gz"
[[WCS]]
arch = "powerpc64le"
git-tree-sha1 = "be7aaae22f16af967e1d1e606203f23219b1ef52"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "781058f89247b808c4188e0de1ae1b76ab1ba18b6e773e9ab42a2de2db4104ca"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+1/WCS.v7.6.0.powerpc64le-linux-gnu.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "e72c1e7a480d423074a4690f977f22014fda50bf"
os = "macos"

    [[WCS.download]]
    sha256 = "7d6cfa141bbed4f4da4b1b82eef2cc2ab415fed9d3fa26ac3731a3d2ca51cdaf"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+1/WCS.v7.6.0.x86_64-apple-darwin.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "147914774234e9dd452d5917e0d96c7bc34f10a2"
libc = "glibc"
os = "linux"

    [[WCS.download]]
    sha256 = "257a1b7e27987983731ab7d8ebc466345e5f31c16408d90af95d92438d1ab0de"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+1/WCS.v7.6.0.x86_64-linux-gnu.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "4ceb963f64e3397a91897ccdc077719c039d0ad6"
libc = "musl"
os = "linux"

    [[WCS.download]]
    sha256 = "4d68b65cda71d5abe63144ab8a45ca6ded4e6bf0359b19f50a1abaaa5c57bf45"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+1/WCS.v7.6.0.x86_64-linux-musl.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "8dc4ab2184431c47b58b2769b2ca8e8fbfc705a1"
os = "freebsd"

    [[WCS.download]]
    sha256 = "6be28107484479ab2d3dcc5ffaca30eec177eb20e3e79183aa37a5037c1ef5f3"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+1/WCS.v7.6.0.x86_64-unknown-freebsd.tar.gz"
[[WCS]]
arch = "x86_64"
git-tree-sha1 = "f480b8c7ac0f60ca15e13a61a9b2b4f2f4f5757d"
os = "windows"

    [[WCS.download]]
    sha256 = "e37047a5834a072b0e2276cc6e155e9434928ffc3b6174558f5fd3a1d89db697"
    url = "https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/download/WCS-v7.6.0+1/WCS.v7.6.0.x86_64-w64-mingw32.tar.gz"
