# Autogenerated wrapper script for WCS_jll for i686-w64-mingw32
export libwcs

JLLWrappers.@generate_wrapper_header("WCS")
JLLWrappers.@declare_library_product(libwcs, "libwcs.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libwcs,
        "bin\\libwcs.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
